"""Generate js/currency-names.js: ISO 4217 code -> name for the fiat set.

Codes come from open.er-api.com (166 authoritative fiat codes).
Names come from @fawazahmed0/currency-api currencies.json, falling back to
a hand-curated table for anything the source lacks.
"""
import json
import os
import urllib.request

CODES_URL = 'https://open.er-api.com/v6/latest/USD'
NAMES_URL = 'https://cdn.jsdelivr.net/npm/@fawazahmed0/currency-api@latest/v1/currencies.json'

# Codes whose name the upstream source renders poorly or generically.
OVERRIDES = {
    'XAU': 'Gold (troy ounce)',
    'XAG': 'Silver (troy ounce)',
    'XPT': 'Platinum (troy ounce)',
    'XPD': 'Palladium (troy ounce)',
    'XDR': 'IMF Special Drawing Rights',
    'XPF': 'CFP Franc',
    'XAF': 'Central African CFA Franc',
    'XOF': 'West African CFA Franc',
    'XCD': 'East Caribbean Dollar',
    'XCG': 'Caribbean Guilder',
    'ANG': 'Netherlands Antillean Guilder',
    'SLE': 'Sierra Leonean Leone',
    'ZWG': 'Zimbabwe Gold',
    'VED': 'Venezuelan Bolívar (digital)',
    'VES': 'Venezuelan Bolívar',
    'MRU': 'Mauritanian Ouguiya',
    'STN': 'São Tomé & Príncipe Dobra',
    'CLF': 'Chilean Unit of Account',
    'FOK': 'Faroese Króna',
    'KID': 'Kiribati Dollar',
    'XAU': 'Gold (troy ounce)',
    'XAG': 'Silver (troy ounce)',
    'XPT': 'Platinum (troy ounce)',
    'XPD': 'Palladium (troy ounce)',
    'VED': 'Venezuelan Bolívar (digital)',
}


def get_json(url):
    with urllib.request.urlopen(url, timeout=25) as resp:
        return json.loads(resp.read().decode('utf-8'))


def main():
    er = get_json(CODES_URL)
    codes = sorted(er['rates'].keys())

    names_raw = get_json(NAMES_URL)
    names = {k.upper(): v for k, v in names_raw.items()}

    missing = [c for c in codes if c not in names]
    table = {}
    for code in codes:
        table[code] = OVERRIDES.get(code) or names.get(code) or code

    lines = []
    lines.append("'use strict';")
    lines.append('')
    lines.append('/**')
    lines.append(' * ISO 4217 currency names, keyed by 3-letter code.')
    lines.append(' * Covers every fiat currency returned by the live rate providers.')
    lines.append(' * Generated by tools/gen_currency_names.py — edit that, not this file.')
    lines.append(' */')
    lines.append('const CURRENCY_NAMES = {')
    for code in codes:
        lines.append("  %s: %s," % (code, json.dumps(table[code], ensure_ascii=False)))
    lines.append('};')
    lines.append('')
    lines.append('if (typeof module !== \'undefined\' && module.exports) module.exports = CURRENCY_NAMES;')
    lines.append('')

    out = os.path.join(
        os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
        'js', 'currency-names.js')
    with open(out, 'w', encoding='utf-8', newline='\n') as f:
        f.write('\n'.join(lines))

    print('codes:', len(codes))
    print('missing names:', missing)
    print('written:', out)


if __name__ == '__main__':
    main()
